#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh
test_exit_code=0


run() {
	{ IFS= read -r -d '' write_in || :; } <<-EOF
	    code
	$1$2
	    code
	EOF


	{ IFS= read -r -d '' expect_out || :; } <<-EOF
	<pre><code>
	code
	$2
	code
	</code></pre>
	EOF


	write_in_expect_out || test_exit_code=1
}


# spaces
run '    ' '  '

# tabs
run '	' '		'


exit "$test_exit_code"



