#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh


{ IFS= read -r -d '' write_in || :; } <<-'EOF'
    text
```
code
```
    text
```
code
```
EOF


{ IFS= read -r -d '' expect_out || :; } <<-'EOF'
<pre><code>
text
</code></pre>
<pre><code>
code
</code></pre>
<pre><code>
text
</code></pre>
<pre><code>
code
</code></pre>
EOF


write_in_expect_out



