#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh


{ IFS= read -r -d '' write_in || :; } <<-'EOF'
```
code
```
text
```
code
```
text
EOF


{ IFS= read -r -d '' expect_out || :; } <<-'EOF'
<pre><code>
code
</code></pre>
<p>
text<br />
</p>
<pre><code>
code
</code></pre>
<p>
text<br />
</p>
EOF


write_in_expect_out



