#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh
test_exit_code=0


run() {
	{ IFS= read -r -d '' write_in || :; } <<-EOF
	$1text
	EOF


	{ IFS= read -r -d '' expect_out || :; } <<-EOF
	<h$2>text</h$2>
	EOF


	write_in_expect_out || test_exit_code=1
}


# Spaces
run '# ' '1'
run '## ' '2'
run '### ' '3'
run '#### ' '4'
run '##### ' '5'
run '###### ' '6'

# Tabs
run '#	' '1'
run '##	' '2'
run '###	' '3'
run '####	' '4'
run '#####	' '5'
run '######	' '6'

# Multi-space
run '#  ' '1'

# Multi-tab
run '#		' '1'

exit "$test_exit_code"



