#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh
test_exit_code=0


run() {
	{ IFS= read -r -d '' write_in || :; } <<-EOF
	text
	$1=$2
	EOF


	{ IFS= read -r -d '' expect_out || :; } <<-'EOF'
	<h1>text</h1>
	EOF


	write_in_expect_out || test_exit_code=1
}


# Spaces
run ' ' ''
run '' ' '
run ' ' ' '


# Tabs
run '	' ''
run '' '	'
run '	' '	'


# Mixed spaces and tabs
run ' 	' ' 	'
run '	 ' '	 '


exit "$test_exit_code"



