#!/usr/bin/env bash
set -o errexit
source ./tests/.local/lib/write-in-expect-out.sh
test_exit_code=0


run() {
	{ IFS= read -r -d '' write_in || :; } <<-EOF
	text
	$1
	EOF


	{ IFS= read -r -d '' expect_out || :; } <<-EOF
	<${2}>text</${2}>
	EOF


	write_in_expect_out || test_exit_code=1
}


run '=' 'h1'
run '==' 'h1'
run '-' 'h2'
run '--' 'h2'


exit "$test_exit_code"



